# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_loop <- function(temp, t_min, r, fun_length, nlimit, para_0, para_i, var_func, vf_user, trace, rf, lower, upper, fun, loss_0, k, loss_opt, para_opt, dyn_rf, maxgood, ac_acc, stopac) {
    .Call('optimization_main_loop', PACKAGE = 'optimization', temp, t_min, r, fun_length, nlimit, para_0, para_i, var_func, vf_user, trace, rf, lower, upper, fun, loss_0, k, loss_opt, para_opt, dyn_rf, maxgood, ac_acc, stopac)
}

