# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

var_funcc <- function(para_0, fun_length, rf) {
    .Call('optimization_var_funcc', PACKAGE = 'optimization', para_0, fun_length, rf)
}

main_loop <- function(temp, t_min, r, fun_length, nlimit, para_0, para_i, var_func, vf_user, trace, rf, lower, upper, fun, loss_0, k, loss_opt, para_opt, dyn_rf, maxgood, ac_acc, stopac) {
    .Call('optimization_main_loop', PACKAGE = 'optimization', temp, t_min, r, fun_length, nlimit, para_0, para_i, var_func, vf_user, trace, rf, lower, upper, fun, loss_0, k, loss_opt, para_opt, dyn_rf, maxgood, ac_acc, stopac)
}

